export const user = {
  login: 'andremartinsdev',
  id: 26258891,
  node_id: 'MDQ6VXNlcjI2MjU4ODkx',
  avatar_url: 'https://avatars.githubusercontent.com/u/26258891?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/andremartinsdev',
  html_url: 'https://github.com/andremartinsdev',
  followers_url: 'https://api.github.com/users/andremartinsdev/followers',
  following_url: 'https://api.github.com/users/andremartinsdev/following{/other_user}',
  gists_url: 'https://api.github.com/users/andremartinsdev/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/andremartinsdev/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/andremartinsdev/subscriptions',
  organizations_url: 'https://api.github.com/users/andremartinsdev/orgs',
  repos_url: 'https://api.github.com/users/andremartinsdev/repos',
  events_url: 'https://api.github.com/users/andremartinsdev/events{/privacy}',
  received_events_url: 'https://api.github.com/users/andremartinsdev/received_events',
  type: 'User',
  site_admin: false,
  name: 'André Martins',
  company: 'BMS LTDA',
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: 'Desenvolvedor C#, Vuejs  e NodeJs',
  twitter_username: null,
  public_repos: 9,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2017-03-07T19:09:19Z',
  updated_at: '2021-10-18T21:10:54Z'
}