import '@testing-library/jest-dom'
import { starred } from "../../__mocks__/starred";
import api from "../../services/client";
import { repos } from "../../__mocks__/repos";
import { user } from "../../__mocks__/user";
import axios from "axios";

describe("test requests for github api", () => {
   
    it("must return an object array containing the items the user starred", async () => {
        const { data } = await api.get(`/andremartinsdev/starred`, {
            headers: {
                Authorization: 'Bearer ' + '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'
            }
        })
        expect(data).toEqual(starred)
    })


    it("should return an object array containing the repositories", async () => {
        const { data } = await api.get(`/EriksJunior/repos`, {
            headers: {
                Authorization: 'Bearer ' + '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'
            }
        })
        expect(data).toMatchObject(repos)
    })


    it("should return an object array containing the user", async () => {
        const { data } = await api.get(`/andremartinsdev`, {
            headers: {
                Authorization: 'Bearer ' + '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'
            }
        })
        expect(data).toMatchObject(user)
    })


   
    it("must return the user's token that is generated by server.js (server to handle authentication with the api)", async () => {
        const { data } = await axios.get('http://localhost:3002/auth/token')
        expect(data).toMatchObject({"token": data.token})
    })
})

